# Generated by Django 6.0.3 on 2026-03-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pieteikums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosaukums', models.CharField(max_length=200)),
                ('apraksts', models.TextField()),
                ('statuss', models.CharField(default='NEW', max_length=50)),
            ],
        ),
    ]
